### ISSUE TITLE
Crash on serialization?

### ISSUE THREAD

**Issue by Darkhax** [Caltinor/DeathGenerator#2]
[crash-2021-11-03_00.41.54-server.txt](https://github.com/Caltinor/DeathGenerator/files/7464750/crash-2021-11-03_00.41.54-server.txt)

**Comment by Caltinor** [comment]
I have no idea why that would be happening. Looks like it's starting from melon's mod. Mixin issue?

**Comment by Darkhax** [comment]
We're looking into this more. Just wanted to add the following trace, this happened when a player died near the deathgen. https://gist.github.com/Darkhax/2bf94d03724361b5094c3154a458b5a0

**Comment by Caltinor** [comment]
Another involving melon's mod. Something is not compatible. What is the `replaceChunk` method supposed to do?
